// Code generated by protoc-gen-go. DO NOT EDIT.
// source: guard.proto

package guard

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	GsfId                int64    `protobuf:"varint,3,opt,name=gsfId,proto3" json:"gsfId,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Locale               string   `protobuf:"bytes,5,opt,name=locale,proto3" json:"locale,omitempty"`
	Proxy                *Proxy   `protobuf:"bytes,6,opt,name=proxy,proto3" json:"proxy,omitempty"`
	Device               string   `protobuf:"bytes,7,opt,name=device,proto3" json:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5548e90fe0f5294, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *Account) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Account) GetGsfId() int64 {
	if m != nil {
		return m.GsfId
	}
	return 0
}

func (m *Account) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Account) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *Account) GetProxy() *Proxy {
	if m != nil {
		return m.Proxy
	}
	return nil
}

func (m *Account) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

type Proxy struct {
	Http                 string   `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Https                string   `protobuf:"bytes,2,opt,name=https,proto3" json:"https,omitempty"`
	No                   string   `protobuf:"bytes,3,opt,name=no,proto3" json:"no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proxy) Reset()         { *m = Proxy{} }
func (m *Proxy) String() string { return proto.CompactTextString(m) }
func (*Proxy) ProtoMessage()    {}
func (*Proxy) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5548e90fe0f5294, []int{1}
}

func (m *Proxy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proxy.Unmarshal(m, b)
}
func (m *Proxy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proxy.Marshal(b, m, deterministic)
}
func (m *Proxy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proxy.Merge(m, src)
}
func (m *Proxy) XXX_Size() int {
	return xxx_messageInfo_Proxy.Size(m)
}
func (m *Proxy) XXX_DiscardUnknown() {
	xxx_messageInfo_Proxy.DiscardUnknown(m)
}

var xxx_messageInfo_Proxy proto.InternalMessageInfo

func (m *Proxy) GetHttp() string {
	if m != nil {
		return m.Http
	}
	return ""
}

func (m *Proxy) GetHttps() string {
	if m != nil {
		return m.Https
	}
	return ""
}

func (m *Proxy) GetNo() string {
	if m != nil {
		return m.No
	}
	return ""
}

type ChartsRequest struct {
	Cat                  string   `protobuf:"bytes,1,opt,name=cat,proto3" json:"cat,omitempty"`
	SubCat               string   `protobuf:"bytes,2,opt,name=subCat,proto3" json:"subCat,omitempty"`
	Account              *Account `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChartsRequest) Reset()         { *m = ChartsRequest{} }
func (m *ChartsRequest) String() string { return proto.CompactTextString(m) }
func (*ChartsRequest) ProtoMessage()    {}
func (*ChartsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5548e90fe0f5294, []int{2}
}

func (m *ChartsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartsRequest.Unmarshal(m, b)
}
func (m *ChartsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartsRequest.Marshal(b, m, deterministic)
}
func (m *ChartsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartsRequest.Merge(m, src)
}
func (m *ChartsRequest) XXX_Size() int {
	return xxx_messageInfo_ChartsRequest.Size(m)
}
func (m *ChartsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChartsRequest proto.InternalMessageInfo

func (m *ChartsRequest) GetCat() string {
	if m != nil {
		return m.Cat
	}
	return ""
}

func (m *ChartsRequest) GetSubCat() string {
	if m != nil {
		return m.SubCat
	}
	return ""
}

func (m *ChartsRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type ChartResponse struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Account              *Account `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChartResponse) Reset()         { *m = ChartResponse{} }
func (m *ChartResponse) String() string { return proto.CompactTextString(m) }
func (*ChartResponse) ProtoMessage()    {}
func (*ChartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5548e90fe0f5294, []int{3}
}

func (m *ChartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartResponse.Unmarshal(m, b)
}
func (m *ChartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartResponse.Marshal(b, m, deterministic)
}
func (m *ChartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartResponse.Merge(m, src)
}
func (m *ChartResponse) XXX_Size() int {
	return xxx_messageInfo_ChartResponse.Size(m)
}
func (m *ChartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChartResponse proto.InternalMessageInfo

func (m *ChartResponse) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *ChartResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "Account")
	proto.RegisterType((*Proxy)(nil), "Proxy")
	proto.RegisterType((*ChartsRequest)(nil), "ChartsRequest")
	proto.RegisterType((*ChartResponse)(nil), "ChartResponse")
}

func init() {
	proto.RegisterFile("guard.proto", fileDescriptor_b5548e90fe0f5294)
}

var fileDescriptor_b5548e90fe0f5294 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x86, 0x49, 0xd2, 0xa4, 0xed, 0x55, 0x54, 0xc8, 0x42, 0xc8, 0xaa, 0x18, 0x22, 0x4f, 0x5d,
	0xc8, 0x50, 0x24, 0xf6, 0xaa, 0x42, 0x88, 0x0d, 0x59, 0xac, 0x0c, 0x6e, 0x6c, 0xda, 0x88, 0xca,
	0x67, 0x62, 0x87, 0x8f, 0x1f, 0xc6, 0xff, 0x43, 0xfe, 0x28, 0x82, 0x81, 0x29, 0x7e, 0xce, 0xb9,
	0xc7, 0xaf, 0xee, 0x60, 0xb6, 0x1b, 0x44, 0x2f, 0x1b, 0xd3, 0xa3, 0x43, 0xf6, 0x95, 0xc1, 0x78,
	0xdd, 0xb6, 0x38, 0x68, 0x47, 0xce, 0xa1, 0x3c, 0xe0, 0xae, 0xd3, 0x34, 0xab, 0xb3, 0xe5, 0x94,
	0x47, 0x20, 0x0b, 0x98, 0x18, 0x61, 0xed, 0x3b, 0xf6, 0x92, 0xe6, 0xe1, 0xe2, 0x87, 0x7d, 0xc7,
	0xce, 0x3e, 0xdf, 0x4b, 0x5a, 0xd4, 0xd9, 0xb2, 0xe0, 0x11, 0x7c, 0xd5, 0xe1, 0x8b, 0xd2, 0x74,
	0x14, 0x3d, 0x01, 0xc8, 0x05, 0x54, 0x07, 0x6c, 0xc5, 0x41, 0xd1, 0x32, 0x94, 0x13, 0x91, 0x4b,
	0x28, 0x4d, 0x8f, 0x1f, 0x9f, 0xb4, 0xaa, 0xb3, 0xe5, 0x6c, 0x55, 0x35, 0x0f, 0x9e, 0x78, 0x2c,
	0xfa, 0x2e, 0xa9, 0xde, 0xba, 0x56, 0xd1, 0x71, 0xec, 0x8a, 0xc4, 0xd6, 0x50, 0x86, 0xff, 0x08,
	0x81, 0xd1, 0xde, 0x39, 0x93, 0x32, 0x87, 0xb3, 0x0f, 0xe0, 0xbf, 0x36, 0xe5, 0x8d, 0x40, 0xe6,
	0x90, 0x6b, 0x0c, 0x49, 0xa7, 0x3c, 0xd7, 0xc8, 0x9e, 0xe0, 0x74, 0xb3, 0x17, 0xbd, 0xb3, 0x5c,
	0xbd, 0x0e, 0xca, 0x3a, 0x72, 0x06, 0x45, 0x2b, 0x5c, 0x32, 0xf9, 0xa3, 0x7f, 0xdd, 0x0e, 0xdb,
	0x8d, 0x70, 0xc9, 0x94, 0x88, 0x30, 0x18, 0x8b, 0x38, 0xb4, 0xe0, 0x9b, 0xad, 0x26, 0x4d, 0x1a,
	0x22, 0x3f, 0x5e, 0xb0, 0xdb, 0xa4, 0xe7, 0xca, 0x1a, 0xd4, 0x56, 0x79, 0x7d, 0x27, 0x2d, 0xcd,
	0xea, 0xc2, 0xeb, 0x3b, 0x69, 0x7f, 0x6b, 0xf2, 0x7f, 0x34, 0xab, 0x1b, 0x28, 0xef, 0xfc, 0xbe,
	0xc8, 0x15, 0x4c, 0x1f, 0xd1, 0xc4, 0xc4, 0x64, 0xde, 0xfc, 0x89, 0xbe, 0x48, 0x7c, 0x7c, 0x8b,
	0x9d, 0x6c, 0xab, 0xb0, 0xdf, 0xeb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x1d, 0xed, 0x92,
	0xee, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GuardClient is the client API for Guard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GuardClient interface {
	TopCharts(ctx context.Context, in *ChartsRequest, opts ...grpc.CallOption) (*ChartResponse, error)
}

type guardClient struct {
	cc grpc.ClientConnInterface
}

func NewGuardClient(cc grpc.ClientConnInterface) GuardClient {
	return &guardClient{cc}
}

func (c *guardClient) TopCharts(ctx context.Context, in *ChartsRequest, opts ...grpc.CallOption) (*ChartResponse, error) {
	out := new(ChartResponse)
	err := c.cc.Invoke(ctx, "/Guard/TopCharts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuardServer is the server API for Guard service.
type GuardServer interface {
	TopCharts(context.Context, *ChartsRequest) (*ChartResponse, error)
}

// UnimplementedGuardServer can be embedded to have forward compatible implementations.
type UnimplementedGuardServer struct {
}

func (*UnimplementedGuardServer) TopCharts(ctx context.Context, req *ChartsRequest) (*ChartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TopCharts not implemented")
}

func RegisterGuardServer(s *grpc.Server, srv GuardServer) {
	s.RegisterService(&_Guard_serviceDesc, srv)
}

func _Guard_TopCharts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChartsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardServer).TopCharts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Guard/TopCharts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardServer).TopCharts(ctx, req.(*ChartsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Guard_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Guard",
	HandlerType: (*GuardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TopCharts",
			Handler:    _Guard_TopCharts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guard.proto",
}
